--Police Stations
--Del Perro (-1615.41,-1024.19), Nowhere Rd (2027.18,3437.34), Grapeseed (1680.34,4879.51)
--Fire Stations:
--Marina Dr (1295.4,3667.06)

local delperro = AddBlipForCoord(-1615.41,-1024.19)
SetBlipSprite(delperro, 137)
SetBlipDisplay(delperro, 6)
SetBlipScale(delperro, 0.9)
SetBlipColour(delperro, 38)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString("Del Perro Police Station")
EndTextCommandSetBlipName(delperro)

local sandypd = AddBlipForCoord(2042.54,3469.67)
SetBlipSprite(sandypd, 137)
SetBlipDisplay(sandypd, 6)
SetBlipScale(sandypd, 1.0)
SetBlipColour(sandypd, 38)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString("Sandy Shores Police Station")
EndTextCommandSetBlipName(sandypd)

local grapeseedpd = AddBlipForCoord(1680.34,4879.51)
SetBlipSprite(grapeseedpd, 137)
SetBlipDisplay(grapeseedpd, 6)
SetBlipScale(grapeseedpd, 0.9)
SetBlipColour(grapeseedpd, 38)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString("Grapeseed Police Station")
EndTextCommandSetBlipName(grapeseedpd)

local sandyfd = AddBlipForCoord(1295.4,3667.06)
SetBlipSprite(sandyfd, 137)
SetBlipDisplay(sandyfd, 6)
SetBlipScale(sandyfd, 0.9)
SetBlipColour(sandyfd, 1)
BeginTextCommandSetBlipName("STRING")
AddTextComponentString("Sandy Shores Fire Station")
EndTextCommandSetBlipName(sandyfd)
